name: Python Unit Tests

on:
  push:
    branches:
      - main  # or master, or any branch you want
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # or 3.10, 3.9, etc.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requirements.txt  # we install pytest even if using unittest for better reporting

    - name: Run unit tests
      run: |
        pytest

    - name: Run Black (code formatter)
      run: |
        black --check .
  
    - name: Run Flake8 (code linter)
      run: |
        flake8 . --max-line-length=120 --exclude=venv,Lib,site-packages
